webRequests:
  - url: https://example.com/
    count: 10
    method: GET
  - url: https://blog.example.com
    count: 4
    method: GET
  - url: https://example.com/admin
    count: 2
    method: POST